name: CI Grader
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and run grader
        uses: thotypous/telecom-p1-grader-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
